---
- name: Install supervision agent from deb
  apt:
    deb: "{{ url_deb }}"

- name: Install plugin apache_status
  copy:
    src: apache_status.py
    dest: /usr/lib/check_mk_agent/plugins/apache_status.py
    mode: '0644'
    owner: root
    group: root
  when: "'meta-is_apache_true' in group_names"

- name: Install plugin acronis
  copy:
    src: Check_Acronis.py
    dest: /usr/lib/check_mk_agent/plugins/Check_Acronis.py
    mode: '0644'
    owner: root
    group: root
  when: "'meta-acronis_enabled_true' in group_names"
