---
- hosts: meta-checkmk_enabled_true
  vars:
    ansible_connection: ssh
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_ssh_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
  roles:
    - hoplacloud.check_mk_agent
